services:
  exchangerateprovider.api:
    image: exchangerateproviderapi
    build:
      context: ./backend
      dockerfile: ExchangeRateProvider.API/Dockerfile
    ports:
        - "8756:8080"
        - "8757:8081"
  exchangerateprovider.client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
        - "4201:80"